FROM node:22-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
COPY . .
ARG VITE_APP_URL
ARG VITE_NEXUS_API_URL
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_PRYMEIRA_ACCOUNT_API_URL
ARG VITE_PRYMEIRA_HUB_URL
ARG VITE_PRYMEIRA_PRODUCT_KEY
ARG VITE_PRYMEIRA_AUTH_ENABLED
ARG VITE_FACEBOOK_APP_ID
ARG VITE_FACEBOOK_REDIRECT_URI
ARG VITE_N8N_WEBHOOK_URL
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_DEV_BYPASS=false
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_NEXUS_API_URL=$VITE_NEXUS_API_URL
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_PRYMEIRA_ACCOUNT_API_URL=$VITE_PRYMEIRA_ACCOUNT_API_URL
ENV VITE_PRYMEIRA_HUB_URL=$VITE_PRYMEIRA_HUB_URL
ENV VITE_PRYMEIRA_PRODUCT_KEY=$VITE_PRYMEIRA_PRODUCT_KEY
ENV VITE_PRYMEIRA_AUTH_ENABLED=$VITE_PRYMEIRA_AUTH_ENABLED
ENV VITE_FACEBOOK_APP_ID=$VITE_FACEBOOK_APP_ID
ENV VITE_FACEBOOK_REDIRECT_URI=$VITE_FACEBOOK_REDIRECT_URI
ENV VITE_N8N_WEBHOOK_URL=$VITE_N8N_WEBHOOK_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_DEV_BYPASS=$VITE_DEV_BYPASS
RUN npm run build && npm run build:server

FROM node:22-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/dist ./dist
COPY --from=build /app/dist-server ./dist-server
COPY postgres ./postgres
COPY scripts ./scripts

EXPOSE 3001
CMD ["sh", "-c", "npm run db:migrate && npm start"]
